#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-completion-api
spec:
  environments:
    - name: dev
      build:
        from: radix
#    - name: feature
#      build:
#        from: feature/* # Any repo named feature/*whatever* will trigger this build
    - name: test
      build:
        from: main
  components:
    # Backend API
    - name: backend
      src: ./src 
      variables:
        ASPNETCORE_URLS: "http://*:5000"
        ApplicationInsights__ConnectionString: ""
        ConnectionStrings__AppConfig: ""
        UseAzureAppConfiguration: true
        AzureAd__ClientId: ""
        Authenticator__Instance: ""
        Authenticator__MainApiScope: ""
        Authenticator__CompletionApiClientId: ""
        Authenticator__CompletionApiObjectId: ""
        Authenticator__CompletionApiSecret: ""
        Authenticator__DisableProjectUserDataClaims: false
        Authenticator__DisableRestrictionRoleUserDataClaims: false
      ports:
        - name: http
          port: 5000
      publicPort: http
    
    