apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-completion-api
spec:
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  - name: backend
    image: procosys.azurecr.io/api/procosys-completion:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    secrets: 
    - CONNECTIONSTRINGS__APPCONFIG
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: e8c158a9-a200-4897-9d5f-660e377bddc1
      imageTagName: latest
      variables:
        ASPNETCORE_ENVIRONMENT: 'Development'
        UseAzureAppConfiguration: 'true'
      monitoring: false
      resources:
        requests:
          memory: '1024Mi'
          cpu: '100m'
        limits:
          memory: '1024Mi'
          cpu: '250m'
    # Test environment
    - environment: test
      identity:
        azure:
          clientId: cf2e4cc0-39fe-4604-ad64-98e392987821
      variables:
        ASPNETCORE_ENVIRONMENT: 'Test'
        UseAzureAppConfiguration: 'true'
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '1024Mi'
          cpu: '400m'
        limits:
          memory: '1024Mi'
          cpu: '500m'
    # Prod environment
    - environment: prod
      identity:
        azure:
          clientId: dee65816-6e0b-4816-bafe-ebd7179d5933
      variables:
        ASPNETCORE_ENVIRONMENT: 'Production'
        UseAzureAppConfiguration: 'true'
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '1024Mi'
          cpu: '400m'
        limits:
          memory: '1024Mi'
          cpu: '500m'
  #-------------------------------------------------------
  # External docker image registry
  #
  # username below is client id of app ...
  # ...equinor-procosys-devops-docker-registry with ...
  # ...permission to puch to procosys.azurecr.io container registry
  #-------------------------------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
