#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-completion-api
spec:
  build:
    secrets:
      - FEED_TOKEN
  environments:
    - name: dev
      build:
        from: radix
#    - name: feature
#      build:
#        from: feature/* # Any repo named feature/*whatever* will trigger this build
    - name: test
      build:
        from: main
  components:
    - name: webapi
      src: ./src # Dockerfile location
      secrets:
        - ConnectionStrings__ServiceBus
        - CompletionContext
        - CompletionApiSecret
      variables:
        UseAzureAppConfiguration: false
        ASPNETCORE_URLS: "http://*:5000"
        ApplicationInsights__ConnectionString: ""
        ConnectionStrings__AppConfig: ""
        AzureAd__ClientId: ""
        Authenticator__Instance: ""
        Authenticator__MainApiScope: ""
        Authenticator__CompletionApiClientId: ""
        Authenticator__CompletionApiObjectId: ""
        Authenticator__CompletionApiSecret: ""
        Authenticator__DisableProjectUserDataClaims: false
        Authenticator__DisableRestrictionRoleUserDataClaims: false
        API__Authority:  "https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/"
      ports:
        - name: http
          port: 5000
      publicPort: http