parameters:
  deployment: ''
  dependsOn: ''
  condition: ''
  environment: ''
  testPath: ''

jobs:
  - deployment: '${{ parameters.deployment }}'
    dependsOn: '${{ parameters.dependsOn }}'
    condition: ${{ parameters.condition }}
    pool: 
      vmImage: 'windows-latest'
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
            inputs:
              forceReinstallCredentialProvider: true
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              version: 8.x
          - task: DotNetCoreCLI@2
            displayName: 'Run tests'
            inputs:
              command: 'test'
              projects: '${{ parameters.testPath }}'
              arguments: '-c Release'
              testRunTitle: 'run test'
