version: '3.4'

services:
  equinor.procosys.completion.webapi:
    build:
      args:
        ENV_TYPE: local
        FEED_TOKEN: ${FEED_TOKEN}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    user: "root"