name: build completion

on: 
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required : true
        type: choice
        default: dev
        options: 
          - dev
          - test
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  # runtests:
  #   uses: equinor/procosys-completion-api/.github/workflows/runtests.yaml@github-action-pipeline
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}      
  #   with:
  #     deployment: 'runtests'
  #     environment: 'dev'
  #     testPath: './Equinor.ProCoSys.Completion.sln'

  # build-and-push-docker:
  #   needs: runtests
  #   uses: equinor/procosys-completion-api/.github/workflows/build-and-push-docker.yaml@github-action-pipeline
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
  #     AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
      
  #   with:
  #     repositoryName: procosys-completion
  #     dockerFilePath: ./src/Dockerfile
  #     environment: dev
  #     version: 1.000.0.${{github.run_id}}

  # deploy-to-radix:
  #   needs: build-and-push-docker
  #   uses: equinor/procosys-completion-api/.github/workflows/deploy-to-radix.yaml@github-action-pipeline
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #   with:
  #     applicationName: procosys-completion-api
  #     componentName: backend
  #     imageTag: 1.000.0.${{github.run_id}}
  #     environment: dev

  migrate-dev:
   #needs: build-and-push-docker
   uses: equinor/procosys-completion-api/.github/workflows/migrate-bundle.yaml@github-action-pipeline
   secrets:
     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
     AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
   with:
     workingDirectory: ./src/Equinor.ProCoSys.Completion.Infrastructure
     bundleDirectory: ../Equinor.ProCoSys.Completion.WebApi
     contextName: CompletionContext
     environment: dev