name: Build and push to Azure Container Registry

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Name of the repository within Azure Container Registry"
        required: true
        type: string
      dockerFilePath:
        description: "File to the docker path"
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      version:
        description: 'Deploy version'
        required: true
        type: string
    #outputs:
    #  imageTag:
    #    description: "The tag of the built Docker image"
    #    value: ${{ jobs.build-and-push-docker.outputs.imageTag }}
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_ARTIFACTS_PAT:
        required: true

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
#    outputs:
#      imageTag: ${{ inputs.environment }}-${{ env.CURRENT_DATETIME }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to Azure Container Registry
        run: az acr login --name procosys

      - name: Set NuGet authentication
        env:
          VSS_NUGET_ACCESSTOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }}
        run: |
          dotnet nuget add source https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json \
            --name AzureArtifacts \
            --username "AzureDevOps" \
            --password $VSS_NUGET_ACCESSTOKEN \
            --store-password-in-clear-text

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ${{ inputs.dockerFilePath }}
          push: true
          tags: |
            procosys.azurecr.io/api/${{ inputs.repositoryName }}:${{ inputs.version }}
            procosys.azurecr.io/api/${{ inputs.repositoryName }}:latest