name: Build and push to Azure Container Registry

on:
  workflow_call:
    inputs:
      applicationName:
        description: "Name of the application within Radix"
        required: true
        type: string
      componentName:
        description: "Name of the component within Radix"
        required: true
        type: string
      imageTag:
        description: "The tag of the built Docker image"
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy-to-radix:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # Radix
      - name: 'Get Azure principal token for Radix'
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV
      - name: Deploy on Radix
        uses: equinor/radix-github-actions@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            create pipeline-job
            deploy
            -a ${{ inputs.applicationName }}
            --from-config
            -e ${{ inputs.environment }}
            --component ${{ inputs.componentName }}
            --context playground
            --image-tag-name ${{ inputs.componentName }}=${{ inputs.imageTag }}
            -f 