name: Set up environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string  
    secrets:
      AZURE_CLIENT_ID:
        required: true      
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to Azure Container Registry
        run: az acr login --name procosys
      - name: Get Access Token
        run: |
          echo "Retrieving access token..."
          TOKEN=$(az account get-access-token --resource=https://pkgs.visualstudio.com --query accessToken -o tsv)
          echo "FEED_ACCESSTOKEN=$TOKEN" >> $GITHUB_ENV