name: Set up environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string  
    secrets:
      AZURE_CLIENT_ID:
        required: true      
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
    outputs:
      access_token:
        description: "Access token for use in subsequent jobs"
        value: ${{ jobs.setup_env.outputs.access_token }}

jobs:
  setup_env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      access_token: ${{ steps.set_feed_accesstoken.outputs.access_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to Azure Container Registry
        run: az acr login --name procosys
      - name: Get Access Token
        id: set_feed_accesstoken
        #shell: bash
        run: |
          echo "Retrieving access token..."
          TOKEN=$(az account get-access-token --resource=https://pkgs.visualstudio.com --query accessToken -o tsv)
          echo "::set-output name=access_token::$TOKEN"
      - name: Verify Access Token
        run: |
          echo "Access token starts with: $(echo $FEED_ACCESSTOKEN | cut -c1-10)"
          echo "Access token length: $(echo -n $FEED_ACCESSTOKEN | wc -c)"
        env:
          FEED_ACCESSTOKEN: ${{ steps.set_feed_accesstoken.outputs.access_token }}           

