name: Deploy Radix Application to new Environment

on:
  workflow_call:
    inputs:
      applicationName:
        description: "Name of the application within Radix"
        required: true
        type: string
      toEnvironment:
        description: 'Environment to promote to'
        required: true
        type: string
      fromEnvironment:
        description: 'Environment to promote from'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy-to-radix:
    runs-on: ubuntu-latest
    environment: ${{ inputs.toEnvironment }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Get Azure principal token for Radix'
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV
      - name: Promote on Radix
        uses: equinor/radix-github-actions@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            create pipeline-job
            promote
            -a ${{ inputs.applicationName }}
            --from-config
            --from-environment ${{ inputs.fromEnvironment }}
            --to-environment ${{ inputs.toEnvironment }} 
            --context playground
            --use-active-deployment