name: Test and Deploy

on:
  workflow_call:
    inputs:
      deployment:
        description: 'Deployment type'
        required: false
        type: string
      environment:
        description: 'Target environment'
        required: true
        type: string
      testPath:
        description: 'Path to the test project'
        required: true
        type: string
    secrets:
      FEED_ACCESSTOKEN:
        required: true

jobs:
  runtests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Verify Access Token
        run: |
          echo "Access token starts with: $(echo $FEED_ACCESSTOKEN | cut -c1-10)"
          echo "Access token length: $(echo -n $FEED_ACCESSTOKEN | wc -c)"
        env:
          FEED_ACCESSTOKEN: ${{ env.FEED_ACCESSTOKEN }}              
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dotnet ef
        run: dotnet tool install -g dotnet-ef          

      - name: Configure NuGet source
        run: |
          dotnet nuget add source --name ProCoSysOfficial \
              --username statoildeveloper \
              --password $FEED_ACCESSTOKEN \
              --store-password-in-clear-text \
              https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json
        env:
          FEED_ACCESSTOKEN: ${{ env.FEED_ACCESSTOKEN }}
      - name: Run tests
        run: |
          cd src/
          dotnet test ${{ inputs.testPath }} -c Release --logger "trx"
        env:
          DOTNET_NOLOGO: true
        
      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/*.trx'

      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.environment }}"
          echo "Using deployment type: ${{ inputs.deployment }}"